### PR TITLE
Allowed Fastcraft tweaker

### PR DESCRIPTION
**Pull request by liach**
Close if you do not want to accept this.

### CODE REVIEW

**Comment by Dockter** [comment]
Can you provide a link so I can test this?

**Comment by liach** [comment]
Unfortunately I am at school and can not make a production plugin jar right now. But [here](http://forum.industrial-craft.net/index.php?page=Thread&threadID=10820) is official fastcraft thread and you can find the releases in first page and betas in late comments. Or beta here: http://files.player.to/tmp/fastcraft-1.22-ctest17.jar (fixed much bugs from 1.21)

**Comment by Dockter** [comment]
I'll need a repo link if you've made changes to this.

**Comment by Dockter** [comment]
That project also uses their own obfuscation generator, so unless you have an un-obsfuscated repo for me to look at this isn't going to be approved.

**Comment by liach** [comment]
Is this for glitching code prevention or some other purposes? Fastcraft is closed source and you can find the author [here](https://github.com/sfPlayer1), who is also the current maintainer of IndustrialCraft 2.

**Pull request closed without merging**
